### ISSUE TITLE
Move the services declaration to Pawns manifest

### ISSUE THREAD

**Issue by Ayman-apps** [pawns-app/android-pawns-sdk-demo#3]
Can you put the services declaration in Pawns manifest rather than app manifest. This is causing issues with google play review.
Just the services not the permission.

The below code:
 <service
            android:name="com.pawns.sdk.internal.service.PeerServiceForeground"
            android:exported="false"
            android:foregroundServiceType="dataSync"/>
        <service
            android:name="com.pawns.sdk.internal.service.PeerServiceBackground"
            android:exported="false" />

**Comment by LaurynasM-iproyal** [comment]
Unfortunately no. There are a couple of reasons for that. First of all, it does not matter for google where service is declared, because when you package your application into a bundle all AndroidManifest.xml files get merged into one and that is all they see. Secondly some SDK users use only one type of service - background or foreground. In their case they need to declare only one service.
